version: '3.7'

services:
  app:
    build: .
    ports:
      - 8100:8100
    volumes:
      - .:/home/python/app
    depends_on:
      - pg_db

  pg_db:
    image: postgres:16.3
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: micro_videos
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: