GET http://localhost:8000/categories/

###
GET http://localhost:8000/categories/3c55db16-4d07-4b73-b1a4-d000705c897f/

###
POST http://localhost:8000/categories/
Content-Type: application/json

{
    "name": "Movie"
}

###
PUT http://localhost:8000/categories/3c55db16-4d07-4b73-b1a4-d000705c897f/
Content-Type: application/json

{
    "name": "Movie11111",
    "description": "some desc",
    "is_active": true
}

###
DELETE http://localhost:8000/categories/3c55db16-4d07-4b73-b1a4-d000705c897f/
